name=cacanny
version=0.0.1
author=Francis James Franklin
maintainer=Francis James Franklin <fjf@alinameridon.com>
sentence=CAN bus library with backends for various CAN controllers.
paragraph=CAN bus library with backends for various CAN controllers.
category=Communications
url=https://github.com/FJFranklin/cacanny
architectures=*
depends=
